import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiase bg-neutral-100`}
      >
        <nav className="flex justify-around bg-neutral-200 text-neutral-900 align-middle py-2 ">
          <Link className="" href="/">
            <img src="https://place-hold.it/80x80&text=logo&fontsize=18" alt="logo" />
          </Link>
       
          <ul className="flex justify-center flex-col">
            <Link className="" href="/tickets">
              <li className="font-bold bg-neutral-400 py-2 px-6 ">
                  Notas
                {/* <button className="font-bold bg-neutral-400 py-2 px-6 flex">
                </button> */}
              </li>
            </Link>
          </ul>
          <div>
            {/* login */}
            <img src="https://place-hold.it/80x80&text=user&fontsize=18" alt="logo" />
          </div>

        </nav>

        <section className="bg-neutral-100 flex justify-center w-full h-full">

          {children}
        </section>
      </body>
    </html>
  );
}
