import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from '@/app/context/AuthUserContext';
import ProfileAvatar from "@/components/profile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiase bg-neutral-100`}
        >
          <nav className="flex justify-between bg-neutral-200 text-neutral-900 align-middle items-center py-2 px-20 ">
            <Link className="" href="/">
              <img src="https://place-hold.it/80x80&text=logo&fontsize=18" alt="logo" />
            </Link>
        
            <ul className="flex justify-center w-full h-10 ">
              <Link className="px-4" href="/tickets">
                <li className="font-bold bg-neutral-400 py-2 px-6 ">
                    Notas
                  {/* <button className="font-bold bg-neutral-400 py-2 px-6 flex">
                  </button> */}
                </li>
              </Link>
              <Link className="px-4" href="/invoices">
                <li className="font-bold bg-neutral-400 py-2 px-6 ">
                    Cortes
                  {/* <button className="font-bold bg-neutral-400 py-2 px-6 flex">
                  </button> */}
                </li>
              </Link>
              <Link className="px-4" href="/clients">
                <li className="font-bold bg-neutral-400 py-2 px-6 ">
                    Clientes
                  {/* <button className="font-bold bg-neutral-400 py-2 px-6 flex">
                  </button> */}
                </li>
              </Link>
            </ul>
            <ProfileAvatar />

          </nav>

          <section className="bg-neutral-100 flex justify-center w-full h-full">
              {children}
          </section>
        </body>
      </AuthProvider>

    </html>
  );
}
